---
version_role: 1.0.0

liste_install: [ 'monit', 'lm_sensors', 'lm_sensors-libs', 'sysstat', 'monitorix',
                 'wget', 'rrdtool', 'rrdtool-perl', 'perl-libwww-perl', 'perl-MailTools',
                 'perl-MIME-Lite', 'perl-CGI', 'perl-DBI', 'perl-XML-Simple',
                 'perl-Config-General', 'perl-HTTP-Server-Simple', 'perl-IO-Socket-SSL',
                 'cockpit', 'cockpit-tests', 'cockpit-composer', 'cockpit-dashboard',
                 'cockpit-packagekit', 'cockpit-networkmanager', 'cockpit-system' ]

architecture_processeur: "{{ ansible_architecture }}"


# Mot de passe du compte admin permettant l'accès à l'interface web
cpte_admin: admintux

# Mot de passe du compte utilisateur permettant l'accès à l'interface web
cpte_utils: Utilisateur

# Configuration du port d'écoute permettant l'accès à l'interface web.
port_ecoute: 5962

# Autoriser l'utilisation du compte invité en lecture seule. Les valeurs sont true ou false
autorisation_guest: true

# Autoriser l'accès en local. Les valeurs sont true ou false
autorisation_localhost: false

# Utiliser ou pas le ssl pour l'interface web. Valeur enable ou disable.
ssl_enable: false

# Les valeurs ci-dessous doivent être exprimées en seconde(s)
temps_demarrage: 5
temps_sureveillance: 10
