---
- name: restart monitorix
  ansible.builtin.systemd:
    name: monitorix
    state: restarted
    enabled: true

- name: restart monit
  ansible.builtin.systemd:
    name: monit
    state: restarted
    enabled: true
