---
- name: Installation de l'agent qemu pour les VM Proxmox.
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: latest
    update_cache: false

- name: DÃ©marrage de l'agent qemu.
  ansible.builtin.systemd_service:
    name: qemu-guest-agent
    state: restarted
    enabled: true
