---
installe_packages: ['fail2ban', 'firewalld', 'unattended-upgrades', 'libpam-tmpdir',
                    'auditd', 'needrestart', 'libpam-passwdqc', 'debsums']

# Liste d'adresses IP Ã  ne pas bannir.
fail2ban_ssh_whitelist: 1.1.1.1
